version: 2
updates:
- package-ecosystem: pip
  directory: jupyter
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: pip
  directory: jupyter-scipy
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: pip
  directory: jupyter-pytorch-full
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: pip
  directory: jupyter-tensorflow-full
  schedule:
    interval: weekly
    day: friday
