name: Build Notebook Images

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for base image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/haoxins/kubeflow-base
        tags: |
          type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,format=short
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push base image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-base.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Extract metadata for Jupyter image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/haoxins/kubeflow-jupyter
        tags: |
          type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,format=short
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Jupyter image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-jupyter.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Extract metadata for SciPy image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/haoxins/kubeflow-scipy
        tags: |
          type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,format=short
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push SciPy image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-scipy.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Extract metadata for TensorFlow image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/haoxins/kubeflow-tensorflow
        tags: |
          type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,format=short
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push TensorFlow image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-tensorflow.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Build and push TensorFlow full image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-tensorflow-full.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Extract metadata for PyTorch image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/haoxins/kubeflow-pytorch
        tags: |
          type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,format=short
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push PyTorch image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-pytorch.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}

    - name: Build and push PyTorch full image
      uses: docker/bake-action@v1
      with:
        files: |
          .github/workflows/bake-pytorch-full.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: bake-platform
        push: ${{ github.event_name != 'pull_request' }}
